enable_color: true
enable_depth: true
enable_sync: false
align_depth.enable: true
enable_rgbd: false
pointcloud.enable: false
colorizer.enable: false
enable_infra: false
enable_infra1: false
enable_infra2: false
enable_gyro: false
enable_accel: false
depth_module.depth_profile: 848x480x30
rgb_camera.color_profile: 1280x720x30
