pick_target_base_node:
  ros__parameters:
    input_topic: /pick_target_3d
    output_topic: /pick_target_base
    target_frame: base_link
    transform_timeout_sec: 0.2

    require_depth_valid: true

    min_camera_z_m: 0.20
    max_camera_z_m: 1.50

    publish_invalid_targets: true
    log_period_sec: 1.0
