vitis_ai_detector_node:
  ros__parameters:
    model_path: "/home/ubuntu/vitis_ai_work/smartcam_models/models/ssd_adas_pruned_0_95/ssd_adas_pruned_0_95.xmodel"
    detector_mode: "worker"
    script_path: "/home/ubuntu/vitis_ai_work/scripts/ssd_adas_oneshot_json.py"
    worker_script_path: "/home/ubuntu/ros2_ws/src/vitis_ai_detector_pkg/vitis_ai_detector_pkg/vitis_ai_worker.py"
    worker_log_path: "/tmp/vitis_ai_worker.log"
    worker_softmax: "auto"
    input_topic: "/camera/camera/color/image_raw"
    output_topic: "/detections"
    overlay_topic: "/vitis_ai_detector/overlay"
    image_path: "/tmp/vitis_ai_latest.jpg"
    json_path: "/tmp/vitis_ai_detections.json"
    process_period_sec: 0.1
    timeout_sec: 10.0
    publish_empty_detections: true
    publish_overlay: true
    log_period_sec: 0.1
